### ISSUE TITLE
Check arity for scopes

### ISSUE THREAD

**Issue by dogenpunk** [activerecord-hackery/meta_search#19]
When using a checkbox on a form to include a named scope in a search, the value of the form element is automatically passed to the scope regardless of whether or not the scope requires a parameter. I think that the arity should be checked before passing arguments.

**Comment by hachpai** [comment]
Hello! I had the same expect for fiterrific. I've made a fork. As arity for scope and enums doesn't work as expected I use the ArgumentError exception. 

    filterrific_available_filters.each do |filter_name|
        filter_param = filterrific_param_set.send(filter_name)
          next if filter_param.blank? # skip blank filter_params
          begin
            ar_rel = ar_rel.send(filter_name, filter_param)
          rescue ArgumentError #if we have a scope with arity 0 or enum query, we can perform the request without the parameter
            ar_rel = ar_rel.send(filter_name) if (filter_param == 1)
          end
        end
        ar_rel
    end
